# Generated by Django 5.0.13 on 2025-06-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('banner_image', models.ImageField(upload_to='shop/banner')),
                ('create_date', models.DateTimeField(verbose_name='Create Date')),
            ],
        ),
    ]
