# Generated by Django 5.0.13 on 2025-06-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_banner_create_date_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='child_categ_id',
            new_name='child_categ_ids',
        ),
    ]
