# Generated by Django 5.0.13 on 2025-06-10 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_featuredcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('product_image', models.ImageField(upload_to='shop/product')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('published', models.BooleanField(default=False)),
                ('internal_ref', models.CharField(editable=False, max_length=20, unique=True)),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('allow_out_of_stock', models.BooleanField(default=False)),
                ('product_type', models.CharField(choices=[('storable', 'Storable'), ('consumable', 'Consumable')], default='storable', max_length=20)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
