# Generated by Django 5.0.13 on 2025-06-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slider_type', models.CharField(choices=[('new', 'NEW'), ('manual', 'Manual')], default='new', max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('product_ids', models.ManyToManyField(to='shop.product')),
            ],
        ),
    ]
