# Generated by Django 5.0.13 on 2025-06-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_users_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
    ]
