# Generated by Django 5.0.13 on 2025-06-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_saleorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='name',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
