# Generated by Django 5.0.13 on 2025-06-21 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_saleorder_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount Total'),
        ),
        migrations.CreateModel(
            name='SaleOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('qty', models.IntegerField(default=1, verbose_name='Qauntity')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('sale_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.saleorder')),
            ],
        ),
    ]
