# Generated by Django 5.0.13 on 2025-06-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_saleorder_total_amount_saleorderline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorderline',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
