# Generated by Django 5.0.13 on 2025-06-21 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_saleorderline_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderline',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=20),
            preserve_default=False,
        ),
    ]
